create table todo (id integer generated by default as identity, data_para_finalizar date, descricao varchar(255), finalizado boolean, titulo varchar(255), primary key (id));
create table todo (id integer generated by default as identity, data_para_finalizar date, descricao varchar(255), finalizado boolean, titulo varchar(255), primary key (id));
